ALTER TABLE bills ADD COLUMN supplier_name TEXT NOT NULL DEFAULT '';
ALTER TABLE bills ADD COLUMN supplier_address TEXT NOT NULL DEFAULT '';
ALTER TABLE bills ADD COLUMN supplier_phone TEXT NOT NULL DEFAULT '';
ALTER TABLE bills ADD COLUMN supplier_tin TEXT NOT NULL DEFAULT '';
ALTER TABLE bills ADD COLUMN supplier_vat_number TEXT NOT NULL DEFAULT '';
ALTER TABLE bills ADD COLUMN customer_tin TEXT NOT NULL DEFAULT '';